version: "2.2"

services:
  db:
    container_name: app-name-api-db-prod
    hostname: db.prod.local
    image: mysql:8.0.13
    environment:
      - MYSQL_ROOT_PASSWORD=root-password
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=prod-db
      - MYSQL_USER=prod-user
      - MYSQL_PASSWORD=prod-password
    volumes:
      - ./mysql-prod/db:/var/lib/mysql
      - ./mysql-prod/dmp:/var/lib/mydmp
      - ./mysql-prod/init:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306